### ISSUE TITLE
bytearrays not supported

### ISSUE THREAD

**Issue by jtpereyda** [cristianav/PyCRC#1]
The CRC modules needlessly fail when `bytearray` types are given, even though calculations could work. The offending lines in each CRC*.py file are:
````python
            is_string = isinstance(input_data, str)
            is_bytes = isinstance(input_data, bytes)

            if not is_string and not is_bytes:
                raise Exception("Please provide a string or a byte sequence \
                    as argument for calculation.")
````

We could simply exclude this check. Alternatively, we could add an is_bytearray line and add it to the conditional statement. One advantage of removing the check is that we don't exclude other types that should work fine, e.g., subclasses of bytearray.

**Comment by cnopen** [comment]
Hi and thanks for your input.
At first glance I will go for an additional is_bytearray check; _isinstance_ also cares about subclasses so it should address the last concern.

Feel free to modify the files to reflect these changes and create a pull request to integrate them into the main repo.

**Comment by cristianav** [comment]
Sorry for the late reply and thanks for your input.
At first glance I will go for an additional is_bytearray check; isinstance also cares about subclasses so it should address the last concern.

Feel free to modify the files to reflect these changes and create a pull request to integrate them into the main repo.
